trigger:
  branches:
    include:
      - feature/*
      - main
pool: Kolkata
stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: 
        displayName: TerraformInit
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'kolkata'
            backendAzureRmStorageAccountName: 'backendstg03'
            backendAzureRmContainerName: 'aniket'
            backendAzureRmKey: 'strg.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'kolkata'
        - task: TerraformTask@5
          displayName: TerraformApply
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'IndividualCI'))
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'kolkata'



